---
before_script:
  - echo Starting
build:
  script:
    - docker build -t registry.lftechnology.com/sports-admin:latest -f ./docker/Dockerfile .
    - docker push registry.lftechnology.com/sports-admin:latest
    - curl -X POST --user $username:$password https://registry.lftechnology.com/deploy/dev.admin.sports.lftechnology.com
