---
before_script:
  - echo Starting
build:
  script:
    - docker build . -t registry.lftechnology.com/sports:latest
push:
  script:
    - docker push registry.lftechnology.com/sports:latest
deploy:
  script:
    - curl -X POST --user $username:$password https://registry.lftechnology.com/deploy/dev.sports.lftechnology.com
    
