before_script:
  - echo Starting...
deploy:
  tags:
    - shell
  only:
    - master
  script:
    - docker build -t registry.lftechnology.com/sports:stable -f ./docker/Dockerfile .
    - docker push registry.lftechnology.com/sports:stable
    - curl -X POST --user $username:$password https://registry.lftechnology.com/deploy/sports.lftechnology.com
