---
before_script:
  - echo Starting...
build:
  only:
    - dev
  script:
    - docker-compose up web_yarn
    - docker-compose up web_build
    - docker build . -t registry.lftechnology.com/sports:latest
push:
  only:
    - dev
  script:
    - docker build -t registry.lftechnology.com/sports:latest -f ./docker/Dockerfile .
deploy:
  only:
    - dev
  script:
    - curl -X POST --user $username:$password https://registry.lftechnology.com/deploy/dev.sports.lftechnology.com
