--- 
sudo: false
dist: xenial


addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"



before_script: 
  - "pip install --user awscli"
  - "aws configure"
  - "pip3 install envault"
  - "envault --version"
  - "curl -sf https://up.apex.sh/install | sudo sh"


env: 
  global: 
    - "PATH=$HOME/.local/bin:$PATH"

    
jobs: 
  include: 
    - 
      language: node_js
      name: "Deploy APP"
      node_js: "8.10"
      script: "echo \"Deploying app\"\n"
      stage: deploy
    - 
      name: "Deploy ADMIN_APP"
      script: "echo \"Deploying the admin-app\"\n"
    - 
      name: "Deploy API"
      script: |
          echo "Deploying the api"
          cd api
          envault list -secret=sports/api/dev > .env
          up deploy dev