
# linux distribution to be used in VM
dist: xenial

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    
before_script:
  # set up awscli packages
  - pip install --user awscli
  # setup envault packages
  - pip install envault
  - envault --version
  # install apex up
  -  curl -sf https://up.apex.sh/install | sh
  
jobs:
  include:    
    - stage: deploy
      language: node_js
      node_js: "8.10"            
    
      name: "Deploy APP"  
      script: |
                echo "Deploying app"
      
    - script: |
                echo "Deploying the admin-app"

      name: "Deploy ADMIN_APP"

    - script: |
                echo "Deploying the api"
                cd api
                envault list -secret=sports/api/dev > .env
                up stage dev

      name: "Deploy API