version: '2.1'
services:
  web:
    image: 'node:8'
    container_name: 'sports-web'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    ports:
      - '${WEB_PORT:-3000}:3000'
    command: sh -c 'yarn && yarn start'
    networks:
      - sports

  web_yarn:
    image: 'node:8'
    container_name: 'sports-web-yarn'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn'
    networks:
      - sports

  web_build:
    image: 'node:8'
    container_name: 'sports-web-build'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn build'
    networks:
      - sports

  web_build_serve:
    image: 'nginx:1.12'
    container_name: 'sports-web-serve'
    volumes:
      - './dist/:/home/sports/frontend/'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    environment:
      - NGINX_HOST=sports.local
      - NGINX_PORT=80
    working_dir: '/home/sports/frontend/'
    ports:
      - "80:80"
    command: sh -c "nginx -g 'daemon off;'"
    networks:
      - sports

  web_scss_rebuild:
    image: 'node:8'
    container_name: 'sports-web-rebuild'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'npm rebuild node-sass --force'
    networks:
      - sports

networks:
  sports:
    driver: bridge
