version: '2.1'
services:
  chess_api:
    image: 'node:8-alpine'
    restart: always
    volumes:
      - './chess/backend/:/home/chess/backend/'
    working_dir: /home/chess/backend/
    ports:
      - '${CHESS_API_PORT:-5000}:5000'
    command: sh -c 'yarn start'
  chess_api_yarn:
    image: 'node:8-alpine'
    volumes:
      - './chess/backend/:/home/chess/backend/'
    working_dir: /home/chess/backend/
    command: sh -c 'yarn'
  chess_db_migrate:
    image: 'node:8-alpine'
    volumes:
      - './chess/backend/:/home/chess/backend/'
    working_dir: /home/chess/backend/
    command: sh -c 'yarn migrate'
    depends_on:
      chess_db:
        condition: service_healthy
  chess_db_rollback:
    image: 'node:8-alpine'
    volumes:
      - './chess/backend/:/home/chess/backend/'
    working_dir: /home/chess/backend/
    command: sh -c 'yarn rollback'
    depends_on:
      chess_db:
        condition: service_healthy
  chess_db:
    image: 'postgres:10-alpine'
    restart: always
    environment:
      POSTGRES_DB: ${CHESS_DB:-chess}
      POSTGRES_USER: ${CHESS_DB_USER:-chess}
      POSTGRES_PASSWORD: ${CHESS_DB_PASSWORD:-chess}
    ports:
      - '5444:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  sports_web:
    image: 'node:8-alpine'
    volumes:
      - './sports/frontend/:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    ports:
      - '${SPORTS_WEB_PORT:-3000}:3000'
    command: sh -c 'yarn start'
  sports_web_yarn:
    image: 'node:8-alpine'
    volumes:
      - './sports/frontend/:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn'
