version: '2.1'
services:
  web:
    image: 'node:8'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    ports:
      - '${WEB_PORT:-8080}:8080'
    command: sh -c 'yarn start'
    networks:
      - sports_web

  web_yarn:
    image: 'node:8'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn'
    networks:
      - sports_web

  web_build:
    image: 'node:8'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn build'
    networks:
      - sports_web

  web_build_serve:
    image: 'nginx:1.12-alpine'
    volumes:
      - './dist/:/home/sports/frontend/'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    environment:
      - NGINX_HOST=sports.local
      - NGINX_PORT=80
    working_dir: '/home/sports/frontend/'
    ports:
      - "80:80"
    command: sh -c "nginx -g 'daemon off;'"
    networks:
      - sports_web

  web_scss_rebuild:
    image: 'node:8'
    volumes:
      - './:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'npm rebuild node-sass --force'
    networks:
      - sports_web

networks:
  sports_web:
    driver: bridge
