version: '2.1'
services:
  sports_api:
    image: 'node:8-alpine'
    restart: always
    volumes:
      - './backend/:/home/sports/backend/'
    working_dir: /home/sports/backend/
    ports:
      - '${API_PORT:-5000}:5000'
    command: sh -c 'yarn start'
    depends_on:
      sports_db:
        condition: service_healthy
  sports_api_yarn:
    image: 'node:8-alpine'
    volumes:
      - './backend/:/home/sports/backend/'
    working_dir: /home/sports/backend/
    command: sh -c 'yarn'
  sports_db_migrate:
    image: 'node:8-alpine'
    volumes:
      - './backend/:/home/sports/backend/'
    working_dir: /home/sports/backend/
    command: sh -c 'yarn migrate'
    depends_on:
      sports_db:
        condition: service_healthy
  sports_db_rollback:
    image: 'node:8-alpine'
    volumes:
      - './backend/:/home/sports/backend/'
    working_dir: /home/sports/backend/
    command: sh -c 'yarn rollback'
    depends_on:
      sports_db:
        condition: service_healthy
  sports_db:
    image: 'postgres:10-alpine'
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-sports}
      POSTGRES_USER: ${DB_USER:-sports}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sports}
    ports:
      - '${EXPOSED_DB_PORT:-5444}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  sports_web:
    image: 'node:8-alpine'
    volumes:
      - './frontend/:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    ports:
      - '${WEB_PORT:-3000}:8080'
    command: sh -c 'yarn start'
  sports_web_yarn:
    image: 'node:8-alpine'
    volumes:
      - './frontend/:/home/sports/frontend/'
    working_dir: /home/sports/frontend/
    command: sh -c 'yarn'
