version: '2.1'
services:
  web:
    image: 'node:8'
    container_name: 'sports-web'
    volumes:
      - './:/source'
    working_dir: /source
    ports:
      - '${WEB_PORT:-3000}:8080'
    command: sh -c 'yarn && yarn serve'
    networks:
      - sports

  web_yarn:
    image: 'node:8'
    container_name: 'sports-web-yarn'
    volumes:
      - './:/source'
    working_dir: /source
    command: sh -c 'yarn'
    networks:
      - sports

  web_build:
    image: 'node:8'
    container_name: 'sports-web-build'
    volumes:
      - './:/source'
    working_dir: /source
    command: sh -c 'yarn build'
    networks:
      - sports

  web_build_serve:
    image: 'nginx:1.12'
    container_name: 'sports-web-serve'
    volumes:
      - './dist/:/source'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    environment:
      - NGINX_HOST=sports.local
      - NGINX_PORT=80
    working_dir: '/source'
    ports:
      - '80:80'
    command: sh -c "nginx -g 'daemon off;'"
    networks:
      - sports

  web_scss_rebuild:
    image: 'node:8'
    container_name: 'sports-web-rebuild'
    volumes:
      - './:/source'
    working_dir: /source
    command: sh -c 'npm rebuild node-sass --force'
    networks:
      - sports

networks:
  sports:
    driver: bridge
