swagger: "2.0"
info:
  title: Sports API overview
  version: 1.0.0
paths:
  /v1:
    get:
      summary: Display basic information
      description: Displays app name and version
      produces:
        - application/json
      tags:
        - Paths
      responses:
        200:
          description: Working Perfect

