---
before_script:
  - echo Starting
build:
  only:
    - dev
  script:
    - docker build -t registry.lftechnology.com/sports-api:latest -f ./docker/Dockerfile .
    - docker push registry.lftechnology.com/sports-api:latest
    - curl -X POST --user $username:$password https://registry.lftechnology.com/deploy/dev.api.sports.lftechnology.com
